# Site settings
title:          Younlab
description:    ""
baseurl:        "/younlab"
url:            "https://younlab.github.io"

# Author
author:
  name:         Sehyeon Youn
  url:          https://younlab.github.io
  email:        dev.younlab@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10
