# Site settings
title:          Parkdev
description:    ""
baseurl:        ""
url:            "https://parkdev.github.io"

# Author
author:
  name:         Parkdev
  url:          https://parkdev.github.io
  email:        devpark29@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed


# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10
